/*
 * This source file was generated by the Gradle 'init' task
 */
package com.main.RPG_ZERO;

import static com.raylib.Raylib.*;
import static com.raylib.Jaylib.WHITE;

public class App {
    public String getGreeting() {
        InitWindow(500, 500, "Hello World!");
        SetTargetFPS(30);
        while(!WindowShouldClose()) {
            BeginDrawing();
            ClearBackground(WHITE);
            EndDrawing();
        }
        CloseWindow();
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
